backend:
  name: github
  repo: redxtech/meal-time
  branch: master

media_folder: src/assets/images

collections:
  - label: Meals
    name: meals
    files:
      - label: Meals
        name: meals
        file: src/assets/content/meals.json
        fields:
          - label: Meals
            name: meals
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Directions
                name: directions
                widget: markdown
              - label: Ingredients
                name: ingredients
                widget: list
                fields:
                  - { label: Ingredient, name: ingredient, widget: string }
                  - { label: Quantity, name: count, widget: number }
              - label: Type
                name: type
                widget: select
                options: [ Main, Side ]
                default: Main
              - label: Mealtimes
                name: mealtimes
                widget: select
                options: [ Breakfast, Lunch, Dinner ]
                multiple: true
                default: [ Lunch, Dinner ]
    editor:
      preview: false
